[application]

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.wasm_opt]
# The level wasm-opt should target. z is the smallest. 4 is the fastest.
level = "2"

[web.app]

# HTML title tag content
title = "Super Duck Chess"

[web.watcher]

index_on_404 = true

watch_path = ["src", "examples"]

[bundle]
# Bundle identifier
identifier = "io.github.."

# Bundle publisher
publisher = "."

# Bundle icon
icon = ["icons/icon.png"]

# Bundle resources
resources = ["public/*"]

# Bundle copyright
copyright = ""

# Bundle category
category = "Utility"

# Bundle short description
short_description = "Duck chess!"

# Bundle long description
long_description = """
Duck chess!
"""
