[package]
name = "common"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bson = "2.4.0"
getrandom = { version = "0.2.7", features = ["js"] }
serde_with = "2.0"
anyhow = { version = "1.0.58", features = ["backtrace"] }
once_cell = "1.15.0"
